version: '3'

services:
  postgres:
    container_name: stealth-edtech-postgres
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: always
    # env_file: ../.env
    image: postgres:14.6
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ../data:/var/lib/postgresql/data/ # if you want to use a bind folder

    ports:
      - '5433:5432'
